name: opds_robo_librarian
description: An OPDS client for Dart, written in Dart to connect and request data from OPDS feeds and other sources such as Komga
version: 0.1.1
repository: https://github.com/AlexNYC25/opds-robo-librarian
license: MIT

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  dotenv: ^4.2.0
  http: ^1.1.0
  xml: ^6.5.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
